server:
  port: 8080

spring:
  datasource:
    initialization-mode: embedded
    url: jdbc:h2:mem:testdb;MODE=MYSQL
  cache:
    jcache:
      config: classpath:ehcache.xml
  h2:
    console:
      enabled: true
  # defaults for this docker image - vromero/activemq-artemis
  artemis:
    user: artemis
    password: simetraehcapa

services:
  inventory:
    scheme: http
    host: localhost
    port: 8082
    baseContext: api
    version: v1
    endpoints:
      fetchBeerInventory: beer/{beerId}/inventory

