server:
  port: 8080

spring:
  datasource:
    initialization-mode: embedded
  cache:
    jcache:
      config: classpath:ehcache.xml

services:
  inventory:
    scheme: http
    host: localhost
    port: 8082
    baseContext: api
    version: v1
    endpoints:
      fetchBeerInventory: beers/{beerId}/inventory

