server:
  port: 8080

spring:
  datasource:
    initialization-mode: embedded
    url: jdbc:h2:mem:testdb;MODE=MYSQL
  cache:
    jcache:
      config: classpath:ehcache.xml
  h2:
    console:
      enabled: true

services:
  inventory:
    scheme: http
    host: localhost
    port: 8082
    baseContext: api
    version: v1
    endpoints:
      fetchBeerInventory: beers/{beerId}/inventory

